### ISSUE TITLE
Option to ignore untrusted or self signed certificates

### ISSUE THREAD

**Issue by gbrayut** [StackExchange/httpunit#8]
Some internal systems might use a self signed or untrusted TLS certificate. It would be nice if there was an option in the plan to indicate untrusted certificates should be ignored and allow the test to continue. Right now it generates the following error message:

```
==== ny-puppet02: https://ny-puppet02:8140/production/status/no_key DNS=10.7.0.63 (200 T)
ERROR: x509: certificate signed by unknown authority
```

**Comment by captncraig** [comment]
merged in #17
